spring.application.name=PrimeService
spring.mvc.contentnegotiation.default-content-type=application/json

# Enable query parameter content negotiation
spring.mvc.contentnegotiation.favor-parameter=true

# Rename the query parameter from "format" to "accept"
spring.mvc.contentnegotiation.parameter-name=accept

# Map shorthand keywords to their media types
spring.mvc.contentnegotiation.media-types.json=application/json
spring.mvc.contentnegotiation.media-types.xml=application/xml

# Enable Actuator endpoints
#management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.include=metrics,env
management.endpoint.env.show-values=always
